inherit_gem: {}

plugins:
  - rubocop-rails

AllCops:
  TargetRubyVersion: 3.3
  NewCops: enable
  Exclude:
    - 'vendor/**/*'
    - 'vendor/bundle/**/*'
    - 'node_modules/**/*'
    - 'tmp/**/*'
    - 'bin/*'
    - 'db/schema.rb'
Layout/LineLength:
  Max: 120
