# ...existing code...
name: CI

on:
  workflow_dispatch: {}
  pull_request:
    branches: [develop]
  push:
    branches: [main, develop]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3.1'
          bundler-cache: true

      - name: Install dependencies
        run: |
          gem install bundler
          bundle install --jobs 4 --retry 3

      - name: Run RuboCop
        run: |
          bundle exec rubocop --force-exclusion app config lib test Gemfile Rakefile --fail-level error
          # solo falla si hay error grave

      # aplica un formateado para las autocorreciones
      # avisar si hay autocorrecciones locales pendientes
      - name: Run RuboCop auto-correct check (does not commit)
        run: |
          # Ejecutar en modo "check" para evitar modificar el workspace en CI
          bundle exec rubocop --force-exclusion app config lib test Gemfile Rakefile --format simple || true
          echo "Si hay ofensas autocorregibles, ejecútalas localmente:"
          echo "  bundle exec rubocop -A && git add -A && git commit -m 'style: apply rubocop' && git push"

      - name: Prepare DB (test)
        env:
          RAILS_ENV: test
        run: |
          mkdir -p tmp/storage
          RAILS_ENV=test bin/rails db:prepare

      - name: Run tests
        run: |
          bin/rails test
# ...existing code...